import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Header } from './components/Header';
import { Flex, Box, UIProvider } from '@yamada-ui/react';
import { Sidebar } from './components/Sidebar';
import { Footer } from './components/Footer';
// import App from "next/app";
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
          <UIProvider>
            <Header />
            <Flex height='100vh' bg='gray.900' color='white' pt='60px'>
              <Sidebar />
              <Box as='main' flex='1' p={4}>
                {children}
              </Box>
            </Flex>
            <Footer />
          </UIProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
